"""add_media_thumbnails

Revision ID: 759b2d6bccd0
Revises: 249e14807858
Create Date: 2026-05-17 15:09:13.111790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '759b2d6bccd0'
down_revision: Union[str, None] = '249e14807858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'case_media',
        sa.Column(
            'thumbnails',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='{}',
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_media', 'thumbnails')
    # ### end Alembic commands ###
