"""phase4_annotation_intelligence

Revision ID: 9c08dac2316e
Revises: 759b2d6bccd0
Create Date: 2026-05-17 15:32:27.542123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9c08dac2316e'
down_revision: Union[str, None] = '759b2d6bccd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_terms',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('term_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('timeline_markers',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('marker_type', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_expert', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['case_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_revisions',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('revised_by', sa.UUID(), nullable=False),
    sa.Column('previous_body', sa.Text(), nullable=True),
    sa.Column('previous_annotation_type', sa.Text(), nullable=True),
    sa.Column('previous_confidence_level', sa.Text(), nullable=True),
    sa.Column('previous_extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['revised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_taxonomy_refs',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('taxonomy_term_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_term_id'], ['taxonomy_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_id', 'taxonomy_term_id', name='uq_annotation_taxonomy_ref')
    )
    op.add_column('annotations', sa.Column('confidence_level', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'confidence_level')
    op.drop_table('annotation_taxonomy_refs')
    op.drop_table('annotation_revisions')
    op.drop_table('timeline_markers')
    op.drop_table('taxonomy_terms')
    # ### end Alembic commands ###
